name: PR

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: stable

    - name: Rustfmt
      run: cargo fmt -- --check

    - name: Clippy
      run: |
        cargo --version
        cargo clippy --version
        cargo clippy --all-targets --all-features -- -D warnings -W clippy::unwrap_used

    - name: Run tests
      run: cargo test --verbose

    - name: Ensure protos are up to date
      run: cargo publish --dry-run --all-features -p goodmetrics
